requires 'Alt::Crypt::RSA::BigInt';
requires 'App::FatPacker';
requires 'Carp::Always';
requires 'Crypt::CBC';
requires 'Data::MessagePack';
requires 'Data::Structure::Util';
requires 'DateTime';
requires 'Devel::Declare::Lexer';
requires 'Devel::Declare::Lexer::Factory';
requires 'Getopt::Long';
requires 'HTTP::Daemon';
requires 'HTTP::Date';
requires 'HTTP::Proxy::Engine';
requires 'HTTP::Proxy::FilterStack';
requires 'HTTP::Proxy::HeaderFilter::standard';
requires 'HTTP::Request';
requires 'IO::Socket::SSL', '1.42';
requires 'KiokuDB';
requires 'KiokuDB::Util';
requires 'LWP';
requires 'LWP::ConnCache';
requires 'LWP::Simple';
requires 'LWP::UserAgent';
requires 'MIME::Base64';
requires 'Module::Load';
requires 'Module::ScanDeps';
suggests 'Mojo::IOLoop';
suggests 'Mojo::Server::Daemon';
suggests 'Mojolicious::Lite';
requires 'Moose';
requires 'Moose::Util::TypeConstraints';
suggests 'Mozilla::CA';
suggests 'Net::DHCP::Constants';
suggests 'Net::DHCP::Packet';
suggests 'Net::Frame';
suggests 'Net::Frame::Dump::Online';
suggests 'Net::Frame::Layer::DNS';
suggests 'Net::Frame::Layer::DNS::RR';
suggests 'Net::Frame::Layer::ETH';
suggests 'Net::Frame::Layer::IPv4';
suggests 'Net::Frame::Layer::UDP';
suggests 'Net::Frame::Simple';
suggests 'Net::IP';
suggests 'Net::SSLeay', '1.49';
suggests 'Net::Write::Layer';
suggests 'Net::Write::Layer2';
suggests 'NetAddr::IP';
requires 'Nmap::Parser';
requires 'POE';
requires 'Regexp::Common';
requires 'Scalar::Util';
suggests 'Search::GIN::Extract::Class';
suggests 'Search::GIN::Query::Class';
suggests 'Search::GIN::Query::Manual';
requires 'Socket';
requires 'Term::ANSIColor';
requires 'Term::UI';
requires 'Term::Visual';
requires 'Time::Local';
requires 'Unix::PID';
requires 'WWW::Mechanize';
requires 'perl', '5.008001';

on test => sub {
    requires 'Test::Simple';
};
