#!/usr/bin/perl -w

use Nemesis;

my $Init = new Nemesis::Init();
$SIG{'INT'} = sub { $Init->sighandler(); };

use Getopt::Long qw( GetOptions );

GetOptions(
    "s=s"   => \my $SessionName,    # Session start
    "w=s"   => \my $Wrap,           # Wrap an execution script
    "debug" => \my $DebugCli,       # Debug modality
    "m=s"   => \my $M,
);

###XXX: $Wrap should be abs path for now.

if ( defined($Wrap) and defined($SessionName) ) {
    $Init->io->set_debug(1) if defined($DebugCli);
    defined $M
        ? $Init->getModuleLoader()->loadmodules( split( /\,|\,\s/, $M ) )
        : $Init->getModuleLoader()->loadmodules();
    $Init->ml->instance("session")->spawn($SessionName);
    $Init->getSession()->wrap($Wrap);
}
elsif ( defined($Wrap) ) {
    $Init->io->set_debug(1) if defined($DebugCli);
    defined $M
        ? $Init->getModuleLoader()->loadmodules( split( /\,|\,\s/, $M ) )
        : $Init->getModuleLoader()->loadmodules();
    $Init->getSession()->wrap( $Init->getSession->_get_flow($Wrap) );
}

if ( defined($SessionName) and !defined($Wrap) ) {
    $Init->ml->instance("session")->spawn($SessionName);
    $Init->ml->instance("session")->wrap();
}

my $Interface = $Init->ml->atom("VTinterface");
$Interface->run();

