#!/usr/bin/perl -w

use Nemesis;


my $Init = new Nemesis::Init();
$SIG{'INT'} = sub { $Init->sighandler(); };

use Getopt::Long qw( GetOptions );

GetOptions(
    "s=s"   => \my $SessionName,    # Session start
    "w=s"   => \my $Wrap,           # Wrap an execution script
    "debug" => \my $DebugCli,       # Debug modality

);

if ( defined($DebugCli) ) {
	$Init->io->set_debug(1);
    my $Interface = $Init->ml->atom("Resources::Terminterface");
    $Interface->run();

}
elsif ( defined($Wrap) ) {
	$Init->getSession()->wrap($Wrap);
}
elsif ( defined($SessionName) ) {
	$Init->ml->instance("session")->spawn($Wrap);
	$Init->ml->instance("session")->wrap();
}
else {    #VT

    my $Interface = $Init->ml->atom("Resources::VTinterface");
    $Interface->run();

}
